/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package slcomputer.dialogs;

import java.awt.Dimension;
import java.awt.Image;
import java.awt.Rectangle;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import slcomputer.SocketMaster;

/**
 *
 * @author J
 */
public class JDialogChooseBuff extends javax.swing.JDialog {
    private int[] available;
    /**
     * Creates new form JDialogChooseBuff
     */
    public JDialogChooseBuff(java.awt.Frame parent, boolean modal, int mode, int starUsed, int starTotal, int buffHPP, int buffEP, int buffHPM, int buffEM, int buffK, int base) {
        super(parent, modal);
        initComponents();
        setTitle("选择加成");
        jLabelStar.setText("星星数 "+(starTotal-starUsed)+"/"+starTotal);
        int buff[]=new int[5];
        buff[0]=buffHPP; buff[1]=buffEP; buff[2]=buffHPM; buff[3]=buffEM; buff[4]=buffK;
        boolean isRegularBuff;
        if(buff[0]==0 && buff[1]==0 && buff[2]==0 && buff[3]==0 && buff[4]==0){
            isRegularBuff=false;
            buff[0]=buff[1]=buff[2]=1;
        }
        else{
            isRegularBuff=true;
            base=1;
        }
        available=new int[3];
        int i, j=0;
        for(i=0; i<5; i++){
            if(buff[i]>0){
                available[j++]=i;
            }
            if(j>=3){
                break;
            }
        }
        JButton buttons[]=new JButton[3];
        buttons[0]=jButtonBuff0;
        buttons[1]=jButtonBuff1;
        buttons[2]=jButtonBuff2;
        
        ImageIcon icon;
        int imageIndex=4;
        boolean enoughStar;
        for(i=0; i<buttons.length; i++){
            j=base;
            enoughStar=false;
            switch(available[i]){
                case 0:
                case 2:
                    switch(buff[available[i]]){
                        case 2:
                            j*=10;
                            break;
                        case 3:
                            j*=20;
                            break;
                        default:
                            j*=3;
                            break;
                    }
                    imageIndex=available[i]+mode*5;
                    break;
                case 1:
                case 3:
                    switch(buff[available[i]]){
                        case 2:
                            j*=3;
                            break;
                        case 3:
                            j*=5;
                            break;
                        default:
                    }
                    imageIndex=available[i];
                    break;
                default:
                    imageIndex=4;
            }
            switch(buff[available[i]]){
                case 2:
                    if(starTotal-starUsed>=15){
                        enoughStar=true;
                    }
                    break;
                case 3:
                    if(starTotal-starUsed>=30){
                        enoughStar=true;
                    }
                    break;
                default:
                    if(starTotal-starUsed>=3){
                        enoughStar=true;
                    }
            }
            icon=new ImageIcon("TP/buff"+imageIndex+".png");
            icon.setImage(icon.getImage().getScaledInstance(150, -1, Image.SCALE_DEFAULT));
            buttons[i].setVerticalTextPosition(JButton.BOTTOM);
            buttons[i].setHorizontalTextPosition(JButton.CENTER);
            buttons[i].setIcon(icon);
            if(imageIndex==4){
                buttons[i].setText("秒杀敌首忍者");
            }
            else{
                buttons[i].setText(j+"%");
            }
            buttons[i].setEnabled(enoughStar||!isRegularBuff);
        }
        Dimension d=getPreferredSize();
        Rectangle b=parent.getBounds();
        setBounds(b.x+b.width/3-d.width/2, b.y+b.height/2-d.height/2, d.width, d.height);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelStar = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButtonBuff0 = new javax.swing.JButton();
        jButtonBuff1 = new javax.swing.JButton();
        jButtonBuff2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabelStar.setText("jLabel1");

        jButtonBuff0.setText("jButton1");
        jButtonBuff0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuff0ActionPerformed(evt);
            }
        });

        jButtonBuff1.setText("jButton1");
        jButtonBuff1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuff1ActionPerformed(evt);
            }
        });

        jButtonBuff2.setText("jButton1");
        jButtonBuff2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuff2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonBuff0, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonBuff1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonBuff2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonBuff0, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBuff1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBuff2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelStar)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelStar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBuff0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuff0ActionPerformed
        SocketMaster.globalIndex=available[0];
        dispose();
    }//GEN-LAST:event_jButtonBuff0ActionPerformed

    private void jButtonBuff1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuff1ActionPerformed
        SocketMaster.globalIndex=available[1];
        dispose();
    }//GEN-LAST:event_jButtonBuff1ActionPerformed

    private void jButtonBuff2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuff2ActionPerformed
        SocketMaster.globalIndex=available[2];
        dispose();
    }//GEN-LAST:event_jButtonBuff2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuff0;
    private javax.swing.JButton jButtonBuff1;
    private javax.swing.JButton jButtonBuff2;
    private javax.swing.JLabel jLabelStar;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
