/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package slcomputer.dialogs;

import java.awt.Dimension;
import java.awt.Rectangle;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import slcomputer.AccountInfo;
import slcomputer.SLComputer;
import slcomputer.SocketMaster;

/**
 *
 * @author J
 */
public class JDialogLogin extends javax.swing.JDialog {

    /**
     * Creates new form JDialogLogin
     */
    public JDialogLogin(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        for(AccountInfo s:SLComputer.accounts){
            jComboBox1.addItem(s);
        }
        Dimension d=getPreferredSize();
        Rectangle b=SLComputer.mf.getBounds();
        setBounds(b.x+b.width/3-d.width/2, b.y+b.height/3-d.height/2, d.width, d.height);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jCheckBoxRemember = new javax.swing.JCheckBox();
        jButtonOblivia = new javax.swing.JButton();
        jButtonLogin = new javax.swing.JButton();
        jComboBoxServer = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("登陆");

        jLabel1.setText("账号");

        jComboBox1.setEditable(true);
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jCheckBoxRemember.setText("记住账号");

        jButtonOblivia.setText("忘记此账号");
        jButtonOblivia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonObliviaActionPerformed(evt);
            }
        });

        jButtonLogin.setText("登陆");
        jButtonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoginActionPerformed(evt);
            }
        });

        jComboBoxServer.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "APP 1", "APP 2", "APP 3", "APP 5", "APP 9", "APP 11", "APP 13", "APP 21" }));
        jComboBoxServer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxServerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonOblivia)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonLogin))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jComboBoxServer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCheckBoxRemember))
                            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxServer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBoxRemember))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonOblivia)
                    .addComponent(jButtonLogin))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private boolean checkVip(String usr){
        try {
            //System.out.println(SLComputer.des.encrypt("dodozanqie@163.com"));
        } catch (Exception ex) {
            Logger.getLogger(JDialogLogin.class.getName()).log(Level.SEVERE, null, ex);
        }
        String[] myvip={"adf3a08b5ba2b4de0f2059c1ce5e940b0e6c3f499b437449",
                "3b09935ab315abfe0e726668044a274a", // 客观的苍
                "cda10db2bcf27b387f5e513568e6f2810e6c3f499b437449", // 队长
                "64b72dd8fca10b501fb93a5807de4b0a792b4717e7c5b82f", // 雉鸡油奶
                "cb43174fd03ed6806169fb07a0bcd03c", // 吐吐
                "71fd54d8efab4ca75c089891c09ecea3896db44fb926a25b", // 吐吐
                "cad8aff679c01be6fc609ae8dc7da6c8", // 吐吐
                "7a92cd7838cf91697f55f817429f0f957bdeba206119285a", // 吐吐
                "2b5dfc233269e88ec9649cc854c00de2896db44fb926a25b", // 青苑
                ""};
        boolean isvip=false;
        for(String s:myvip){
            try {
                if(usr.equals(SLComputer.des.decrypt(s))){
                    isvip=true;
                    break;
                }
            } catch (Exception ex) {
                Logger.getLogger(JDialogLogin.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        return isvip;
    }
    
    private void jButtonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoginActionPerformed
        SLComputer.cleanLogin();
        AccountInfo account;
        if(jComboBox1.getSelectedIndex()<0){
            account=new AccountInfo();
            account.usr=(String)jComboBox1.getSelectedItem();
            if(account.usr.equals("")){
                return;
            }
        }
        else{
            account=(AccountInfo)jComboBox1.getSelectedItem();
        }
        if(!checkVip(account.usr)){
            JOptionPane.showMessageDialog(this, "请支持正版！", "版权问题", JOptionPane.ERROR_MESSAGE);
            System.exit(1);
        }
        account.fwq=jComboBoxServer.getSelectedIndex();
        SocketMaster.setGlobalIP(account.fwq);
        SocketMaster.arguments[0]=account.usr;
        SocketMaster.arguments[1]=account.psd;
        SocketMaster.arguments[2]=account.fwq;
        SocketMaster.arguments[3]=jCheckBoxRemember.isSelected();
        SocketMaster.cmdGlobal=SocketMaster.c_login;
        SocketMaster sm=new SocketMaster();
        new Thread(sm).start();
        dispose();
    }//GEN-LAST:event_jButtonLoginActionPerformed

    private void jButtonObliviaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonObliviaActionPerformed
        if(jComboBox1.getSelectedIndex()<=0){
            return;
        }
        AccountInfo s=(AccountInfo)jComboBox1.getSelectedItem();
        if(!s.equals("")){
            for(AccountInfo e:SLComputer.accounts){
                if(s.equals(e)){
                    SLComputer.accounts.removeElement(e);
                    jComboBox1.removeAllItems();
                    for(AccountInfo r:SLComputer.accounts){
                        jComboBox1.addItem(r);
                    }
                    SLComputer.saveAccToFile();
                    break;
                }
            }
        }
    }//GEN-LAST:event_jButtonObliviaActionPerformed

    private void jComboBoxServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxServerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxServerActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        if(jComboBox1.getSelectedIndex()<0){
            return;
        }
        AccountInfo acc=(AccountInfo)jComboBox1.getSelectedItem();
        //System.out.println(acc.fwq);
        if(acc!=null && acc.fwq>=0 && acc.fwq<jComboBoxServer.getItemCount()){
            this.jComboBoxServer.setSelectedIndex(acc.fwq);
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLogin;
    private javax.swing.JButton jButtonOblivia;
    private javax.swing.JCheckBox jCheckBoxRemember;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBoxServer;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
