/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package slcomputer.views.dialogs;

import java.awt.Dimension;
import java.awt.Rectangle;
import javax.swing.JOptionPane;
import slcomputer.runnable.SocketAuto;

/**
 *
 * @author J
 */
public class JDialogAutoBB extends javax.swing.JDialog {

    /**
     * Creates new form JDialogAutoBB
     */
    public JDialogAutoBB(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        Dimension d=getPreferredSize();
        Rectangle b=parent.getBounds();
        setBounds(b.x+b.width/3-d.width/2, b.y+b.height/2-d.height/2, d.width, d.height);
        setVisible(true);
    }
    
    public JDialogAutoBB(java.awt.Frame parent, boolean modal, int ml,  double r, int HPPt, int HPMt, int EPt, int EMt, 
            int HPPm, int HPMm, int EPm, int EMm, int sleep) {
        super(parent, modal);
        initComponents();
        jTextFieldLevel.setText(ml+"");
        jTextFieldRate.setText(r+"");
        jTextFieldHPPTarget.setText(HPPt+"");
        jTextFieldHPMTarget.setText(HPMt+"");
        jTextFieldEffectPTarget.setText(EPt+"");
        jTextFieldEffectMTarget.setText(EMt+"");
        jTextFieldHPPMax.setText(HPPm+"");
        jTextFieldHPMMax.setText(HPMm+"");
        jTextFieldEffectPMax.setText(EPm+"");
        jTextFieldEffectMMax.setText(EMm+"");
        jTextFieldSleep.setText(sleep+"");
        Dimension d=getPreferredSize();
        Rectangle b=parent.getBounds();
        setBounds(b.x+b.width/3-d.width/2, b.y+b.height/2-d.height/2, d.width, d.height);
        setVisible(true);
    }
    
    public boolean getFields(){
        try{
            maxLevel=Integer.parseInt(jTextFieldLevel.getText());
            rate=Double.parseDouble(jTextFieldRate.getText());
            HPPTarget=Integer.parseInt(jTextFieldHPPTarget.getText());
            HPMTarget=Integer.parseInt(jTextFieldHPMTarget.getText());
            EffectPTarget=Integer.parseInt(jTextFieldEffectPTarget.getText());
            EffectMTarget=Integer.parseInt(jTextFieldEffectMTarget.getText());
            HPPMax=Integer.parseInt(jTextFieldHPPMax.getText());
            HPMMax=Integer.parseInt(jTextFieldHPMMax.getText());
            EffectPMax=Integer.parseInt(jTextFieldEffectPMax.getText());
            EffectMMax=Integer.parseInt(jTextFieldEffectMMax.getText());
            sleepTime=Integer.parseInt(jTextFieldSleep.getText());
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "请填写合法的数字！", "出错啦！", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldHPPTarget = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldHPPMax = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldHPMTarget = new javax.swing.JTextField();
        jTextFieldHPMMax = new javax.swing.JTextField();
        jTextFieldEffectPTarget = new javax.swing.JTextField();
        jTextFieldEffectPMax = new javax.swing.JTextField();
        jTextFieldEffectMTarget = new javax.swing.JTextField();
        jTextFieldEffectMMax = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jButtonStrategy = new javax.swing.JButton();
        jButtonStart = new javax.swing.JButton();
        jTextFieldSleep = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldLevel = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldRate = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("设置自动试炼");

        jLabel3.setText("buff");

        jLabel6.setText("自身攻防加");

        jLabel7.setText("敌人攻防减");

        jLabel8.setText("忍术效果加");

        jLabel9.setText("忍术效果减");

        jTextFieldHPPTarget.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jTextFieldHPPTarget.setText("400");

        jLabel4.setText("目标");

        jTextFieldHPPMax.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jTextFieldHPPMax.setText("500");

        jLabel5.setText("上限");

        jTextFieldHPMTarget.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jTextFieldHPMTarget.setText("0");

        jTextFieldHPMMax.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jTextFieldHPMMax.setText("0");

        jTextFieldEffectPTarget.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jTextFieldEffectPTarget.setText("55");

        jTextFieldEffectPMax.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jTextFieldEffectPMax.setText("60");

        jTextFieldEffectMTarget.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jTextFieldEffectMTarget.setText("40");

        jTextFieldEffectMMax.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jTextFieldEffectMMax.setText("50");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jTextFieldHPPTarget, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jTextFieldHPPMax, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldHPMTarget, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                            .addComponent(jTextFieldEffectPTarget)
                            .addComponent(jTextFieldEffectMTarget))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldHPMMax, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldEffectPMax, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldEffectMMax, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldHPPTarget, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldHPPMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldHPMTarget, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldHPMMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextFieldEffectPTarget, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldEffectPMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextFieldEffectMTarget, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldEffectMMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jButtonStrategy.setText("查看策略");
        jButtonStrategy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStrategyActionPerformed(evt);
            }
        });

        jButtonStart.setText("开始试炼");
        jButtonStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStartActionPerformed(evt);
            }
        });

        jTextFieldSleep.setText("1000");

        jLabel12.setText("缓冲");

        jLabel13.setText("ms");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonStart)
                    .addComponent(jButtonStrategy)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldSleep, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonStrategy)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jTextFieldSleep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonStart)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setText("自动试炼直到打完第");

        jTextFieldLevel.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jTextFieldLevel.setText("160");

        jLabel2.setText("层");
        jLabel2.setToolTipText("");

        jLabel10.setText("置信胜率：");

        jTextFieldRate.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jTextFieldRate.setText("99");

        jLabel11.setText("%");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldRate, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextFieldRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonStrategyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStrategyActionPerformed
        if(!getFields()){
            return;
        }
        String strategy="选择难度策略：\n"
                + "1. 如果三个难度下有胜率超过"+rate+"%的，选择胜率超过"+rate+"%中最难的；否则\n"
                + "2. 选择胜率最高的。\n"
                + "加buff策略：\n"
                + "1. 如果30星的buff还未达到目标值（自身攻防+"+HPPTarget+"%/敌人攻防-"+HPMTarget+"%/忍术效果+"+EffectPTarget+"%/忍术效果-"+EffectMTarget+"%），加30星buff；否则\n"
                + "2. 如果15星的buff还未达到目标值，加15星buff；否则\n"
                + "3. 如果30星的buff还未达到上限值（自身攻防+"+HPPMax+"%/敌人攻防-"+HPMMax+"%/忍术效果+"+EffectPMax+"%/忍术效果-"+EffectMMax+"%），加30星buff；否则\n"
                + "4. 如果15星的buff还未达到上限值，加15星buff；否则\n"
                + "5. 如果3星的buff还未达到上限值，加3星的buff；否则\n"
                + "6. 如果有秒杀敌首忍者且4项buff都已达到目标值，则选秒杀敌首忍者；否则\n"
                + "7. 加3星buff。";
        JOptionPane.showMessageDialog(this, strategy, "自动策略", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButtonStrategyActionPerformed

    private void jButtonStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStartActionPerformed
        if(!getFields()){
            return;
        }
        SocketAuto auto=new SocketAuto();
        auto.setParameters(maxLevel, rate, HPPTarget, HPPMax, HPMTarget, HPMMax, EffectPTarget, EffectPMax, EffectMTarget, EffectMMax, sleepTime);
        new Thread(auto).start();
        dispose();
    }//GEN-LAST:event_jButtonStartActionPerformed

    
    private int maxLevel;
    private double rate;
    private int HPPTarget;
    private int HPPMax;
    private int HPMTarget;
    private int HPMMax;
    private int EffectPTarget;
    private int EffectPMax;
    private int EffectMTarget;
    private int EffectMMax;
    private int sleepTime;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonStart;
    private javax.swing.JButton jButtonStrategy;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextFieldEffectMMax;
    private javax.swing.JTextField jTextFieldEffectMTarget;
    private javax.swing.JTextField jTextFieldEffectPMax;
    private javax.swing.JTextField jTextFieldEffectPTarget;
    private javax.swing.JTextField jTextFieldHPMMax;
    private javax.swing.JTextField jTextFieldHPMTarget;
    private javax.swing.JTextField jTextFieldHPPMax;
    private javax.swing.JTextField jTextFieldHPPTarget;
    private javax.swing.JTextField jTextFieldLevel;
    private javax.swing.JTextField jTextFieldRate;
    private javax.swing.JTextField jTextFieldSleep;
    // End of variables declaration//GEN-END:variables
}
