/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package slcomputer.views.dialogs;

import java.awt.Dimension;
import java.awt.Image;
import java.awt.Rectangle;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.SwingConstants;
import slcomputer.main.SLComputer;
import slcomputer.runnable.SocketMaster;

/**
 *
 * @author J
 */
public class JDialogChooseMode extends javax.swing.JDialog {

    /**
     * Creates new form JDialogChooseMode
     */
    public JDialogChooseMode(java.awt.Frame parent, boolean modal, int rank, int times, int timesMax, int bestQX, int bestFY) {
        super(parent, modal);
        initComponents();
        String s="";
        switch(timesMax){
            case 0:
                s="(六人阵)";
                break;
            case 1:
                s="(八人阵)";
                break;
            case 2:
                s="(十人阵)";
                break;
            case 3:
                s="(十二人阵)";
                break;
            case 4:
                s="(十四人阵)";
                break;
            case 5:
                s="(十六人阵)";
                break;
            case 6:
                s="(十六人阵)";
                break;
            default:
                s="(未指定)";
        }
        setTitle("究极试炼");
        jLabelRank.setText("当前排名："+(rank==0?"无排名":(""+rank))+s);
        jLabelChallengeTimes.setText("已挑战次数 "+times);
        ImageIcon icon;
        icon=new ImageIcon("TP/SLQX.png");
        icon.setImage(icon.getImage().getScaledInstance(256, -1, Image.SCALE_DEFAULT));
        jButtonQX.setVerticalTextPosition(JButton.BOTTOM);
        jButtonQX.setHorizontalTextPosition(JButton.CENTER);
        jButtonQX.setIcon(icon);
        jButtonQX.setText("最好成绩："+bestQX+"关");
        icon=new ImageIcon("TP/SLFY.png");
        icon.setImage(icon.getImage().getScaledInstance(256, -1, Image.SCALE_DEFAULT));
        jButtonFY.setVerticalTextPosition(JButton.BOTTOM);
        jButtonFY.setHorizontalTextPosition(JButton.CENTER);
        jButtonFY.setIcon(icon);
        jButtonFY.setText("最好成绩："+bestFY+"关");
        Dimension d=getPreferredSize();
        Rectangle b=parent.getBounds();
        setBounds(b.x+b.width/3-d.width/2, b.y+b.height/2-d.height/2, d.width, d.height);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelRank = new javax.swing.JLabel();
        jLabelChallengeTimes = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jButtonFY = new javax.swing.JButton();
        jButtonQX = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabelRank.setText("当前排名");

        jLabelChallengeTimes.setText("已挑战次数");

        jButtonFY.setText("jButton1");
        jButtonFY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFYActionPerformed(evt);
            }
        });
        jButtonFY.setBounds(0, 160, 260, 150);
        jLayeredPane1.add(jButtonFY, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButtonQX.setText("jButton1");
        jButtonQX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonQXActionPerformed(evt);
            }
        });
        jButtonQX.setBounds(0, 0, 260, 150);
        jLayeredPane1.add(jButtonQX, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelRank)
                            .addComponent(jLabelChallengeTimes))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelRank)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelChallengeTimes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonQXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonQXActionPerformed
        SocketMaster.globalIndex=0;
        dispose();
    }//GEN-LAST:event_jButtonQXActionPerformed

    private void jButtonFYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFYActionPerformed
        SocketMaster.globalIndex=1;
        dispose();
    }//GEN-LAST:event_jButtonFYActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonFY;
    private javax.swing.JButton jButtonQX;
    private javax.swing.JLabel jLabelChallengeTimes;
    private javax.swing.JLabel jLabelRank;
    private javax.swing.JLayeredPane jLayeredPane1;
    // End of variables declaration//GEN-END:variables
}
