/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package slcomputer.views.dialogs;

import java.awt.Dimension;
import java.awt.Rectangle;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import slcomputer.main.EnigmaUtil;
import slcomputer.utils.AccountInfo;
import slcomputer.main.SLComputer;
import slcomputer.runnable.CheckVipRunnable;
import slcomputer.runnable.SocketMaster;

/**
 *
 * @author J
 */
public class JDialogLogin extends javax.swing.JDialog {

    /**
     * Creates new form JDialogLogin
     */
    public JDialogLogin(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents(); count=0;
        for(AccountInfo s:SLComputer.accounts){
            jComboBox1.addItem(s);
        }
        Dimension d=getPreferredSize();
        Rectangle b=SLComputer.mf.getBounds();
        setBounds(b.x+b.width/3-d.width/2, b.y+b.height/3-d.height/2, d.width, d.height);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jCheckBoxRemember = new javax.swing.JCheckBox();
        jButtonOblivia = new javax.swing.JButton();
        jButtonLogin = new javax.swing.JButton();
        jComboBoxServer = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("登陆");

        jLabel1.setText("账号");

        jComboBox1.setEditable(true);
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jCheckBoxRemember.setText("记住账号");

        jButtonOblivia.setText("忘记此账号");
        jButtonOblivia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonObliviaActionPerformed(evt);
            }
        });

        jButtonLogin.setText("登陆");
        jButtonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoginActionPerformed(evt);
            }
        });

        jComboBoxServer.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "APP 1", "APP 2", "APP 3", "APP 5", "APP 9", "APP 11", "APP 13", "APP 21", "混服 1", "混服 2", "混服 3", "混服 4", "混服 5", "混服 6", "混服 7", "混服 11", "混服 12", "混服 13", "混服 14", "混服 16", "混服 20", "混服 24", "混服 29", "混服 33", "混服 40", "混服 45", "混服 50", "混服 76", "混服 78", "混服 89", "混服 96", "混服 100", "混服 106", "混服 121", "混服 127", "混服 130", "混服 135", "混服 138", "混服 139", "混服 140", "混服 141", "混服 142", "混服 143", "混服 144", "混服 145", "混服 146", "混服 147", "混服 148", "混服 149", "混服 150", "混服 151", "混服 152", "混服 153", "混服 154", "混服 155", "混服 156", "混服 157", "混服 158", "混服 159", "混服 160" }));
        jComboBoxServer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxServerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonOblivia)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonLogin))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jComboBoxServer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCheckBoxRemember))
                            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxServer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBoxRemember))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonOblivia)
                    .addComponent(jButtonLogin))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void jButtonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoginActionPerformed
        SLComputer.cleanLogin();
        AccountInfo account;
        if(jComboBox1.getSelectedIndex()<0){
            account=new AccountInfo();
            //System.out.println(jComboBox1.getSelectedItem());
            account.usr=(String)jComboBox1.getSelectedItem();
            if(account.usr.equals("")){
                return;
            }
        }
        else{
            account=(AccountInfo)jComboBox1.getSelectedItem();
        }
        account.fwq=jComboBoxServer.getSelectedIndex();
        SocketMaster.arguments[3]=jCheckBoxRemember.isSelected();
        account.usr=account.usr.trim();
        SocketMaster.usrSave=account.usr;
        CheckVipRunnable cvr=new CheckVipRunnable(account);
        new Thread(cvr).start();
        dispose();
    }//GEN-LAST:event_jButtonLoginActionPerformed

    private void jButtonObliviaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonObliviaActionPerformed
        if(jComboBox1.getSelectedIndex()<=0){
            return;
        }
        AccountInfo s=(AccountInfo)jComboBox1.getSelectedItem();
        if(!s.equals("")){
            for(AccountInfo e:SLComputer.accounts){
                if(s.equals(e)){
                    SLComputer.accounts.removeElement(e);
                    jComboBox1.removeAllItems();
                    for(AccountInfo r:SLComputer.accounts){
                        jComboBox1.addItem(r);
                    }
                    SLComputer.saveAccToFile();
                    break;
                }
            }
        }
    }//GEN-LAST:event_jButtonObliviaActionPerformed

    private void jComboBoxServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxServerActionPerformed
        ++count;
    }//GEN-LAST:event_jComboBoxServerActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        if(jComboBox1.getSelectedIndex()<0){
            return;
        }
        AccountInfo acc=(AccountInfo)jComboBox1.getSelectedItem();
        //System.out.println(acc.fwq);
        if(acc!=null && acc.fwq>=0 && acc.fwq<jComboBoxServer.getItemCount()){
            this.jComboBoxServer.setSelectedIndex(acc.fwq);
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLogin;
    private javax.swing.JButton jButtonOblivia;
    private javax.swing.JCheckBox jCheckBoxRemember;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBoxServer;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
    private int count;
}
